linters:
  disable-all: true
  exclude-use-default: false
  enable:
    - deadcode
    - errcheck
    - goimports
    - golint
    - gosimple
    - ineffassign
    - interfacer
    - misspell
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/mkchangelog
